const AccountRouter = require('./AccountRouter');
const BatchRouter = require('./BatchRouter');
const ZoneRouter = require('./ZoneRouter');
const ProductRouter = require('./ProductRouter');
const SupplierRouter = require('./SupplierRouter');
const CustomerRouter = require('./CustomerRouter');
const NotificationRouter = require('./NotificationRouter');
const WareHouseRouter = require('./WareHouseRouter');
const InventoryCheckRouter = require('./InventoryCheckRouter');
const OrderErrorRouter = require('./OrderErrorRouter');
const OrderReturnRouter = require('./OrderReturnRouter');
const OrderReleaseRouter = require('./OrderReleaseRouter');
const OrderPurchaseRouter = require('./OrderPurchaseRouter');
const OrderTransferRouter = require('./OrderTransferRouter');
const EmployeeRouter = require('./EmployeeRouter');
const UploadRouter = require('./UploadRouter');
const CategoryProductRouter = require('./CategoryProductRouter');
const ProposalRouter = require('./ProposalRouter');
const OrderPurchaseMissingRouter = require('./OrderPurchaseMissingRouter');
const UnitRouter = require('./UnitRouter');
const BatchBoxRouter = require('./BatchBoxRouter');
const ShelfRouter = require('./ShelfRouter');
const DashboardRouter = require('./DashboardRouter');
const ProductQuantityLogRouter = require('./ProductQuantityLogRouter');
const BatchMoveLogRouter = require('./BatchMoveLogRouter');
const ReportRouter = require('./ReportRouter');
const BaseUnitProductRouter = require('./BaseUnitProductRouter');
const DialogFlowCXRouter = require('./DialogFlowCX');
const BoxRouter = require('./BoxRouter');

const router = (app) => {
    app.use('/api/account', AccountRouter);
    app.use('/api/batch', BatchRouter);
    app.use('/api/zone', ZoneRouter);
    app.use('/api/product', ProductRouter);
    app.use('/api/supplier', SupplierRouter);
    app.use('/api/customer', CustomerRouter);
    app.use('/api/notification', NotificationRouter);
    app.use('/api/warehouse', WareHouseRouter);
    app.use('/api/inventory-check', InventoryCheckRouter);
    app.use('/api/order-error', OrderErrorRouter);
    app.use('/api/order-return', OrderReturnRouter);
    app.use('/api/order-release', OrderReleaseRouter);
    app.use('/api/order-purchase', OrderPurchaseRouter);
    app.use('/api/order-transfer', OrderTransferRouter);
    app.use('/api/employee', EmployeeRouter);
    app.use('/api/image', UploadRouter);
    app.use('/api/category-product', CategoryProductRouter);
    app.use('/api/proposal', ProposalRouter);
    app.use('/api/order-purchase-missing', OrderPurchaseMissingRouter);
    app.use('/api/unit', UnitRouter);
    app.use('/api/batch-box', BatchBoxRouter);
    app.use('/api/shelf', ShelfRouter);
    app.use('/api/dashboard', DashboardRouter);
    app.use('/api/product-quantity-log', ProductQuantityLogRouter);
    app.use('/api/batch-move-log', BatchMoveLogRouter);
    app.use('/api/report', ReportRouter);
    app.use('/api/base-unit-product', BaseUnitProductRouter);
    app.use('/api/dialog-flow-cx', DialogFlowCXRouter);
    app.use('/api/box', BoxRouter);
};

module.exports = router;
